-- INFORME 1: FECHA_ENTREGA_PROPIEDAD (PROPIEDAD)

SELECT 
FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD 
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'YYYY')='2021'; -- TAMBIEN SE PUEDE USAR LA CLÁUSULA 'EXTRACT' EN VEZ DE 'TO_CHAR'

-- NO ENTREGARÁ NADA PORQUE LA TABLA FUE POBLADA USANDO LA FUNCION 'SYSDATE' 
-- QUE ENTREGA LA FECHA ACTUAL

SELECT 
TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') AS FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD 
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'YYYY')=TO_CHAR(SYSDATE, 'YYYY');

-- VARIABLES DE SUSTITUCIÓN: SIGNO '&' AMDPERSON

-- &MI_VAR 

SELECT 
TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') AS FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD 
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'YYYY')=&ANNO_CONSULTA; -- O TAMBIEN COMO CHAR '&ANNO_CONSULTA'

-- ORACLE REALIZA CONVERSIONES IMPLÍCITAS

-- CASO EST CIVIL Y RENTA

SELECT
NUMRUT_CLI||'-'||DVRUT_CLI AS "RUN CLIENTE",
APPATERNO_CLI||' '||APMATERNO_CLI||' '||NOMBRE_CLI AS "NOMBRE CLIENTE",
RENTA_CLI AS RENTA, FONOFIJO_CLI AS "TELEFONO FIJO", CELULAR_CLI AS CELULAR
FROM CLIENTE
WHERE (ID_ESTCIVIL=3 OR ID_ESTCIVIL=4) AND RENTA_CLI>=800000; --- ARREGLAR


SELECT
NUMRUT_CLI||'-'||DVRUT_CLI AS "RUN CLIENTE",
APPATERNO_CLI||' '||APMATERNO_CLI||' '||NOMBRE_CLI AS "NOMBRE CLIENTE",
RENTA_CLI AS RENTA, FONOFIJO_CLI AS "TELEFONO FIJO", CELULAR_CLI AS CELULAR
FROM CLIENTE
WHERE (ID_ESTCIVIL IN(3,4) AND RENTA_CLI>=800000) OR ID_ESTCIVIL=1;

-- CASO 3

SELECT
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SUELDO ACTUAL",
SUELDO_EMP+SUELDO_EMP+&PORC_AUMENTO AS "SUELDO AUMENTADO",
SUELDO_EMP*&PORC_AUMENTO AS AUMENTO
FROM EMPLEADO
ORDER BY AUMENTO DESC; -- PARA EL ORDER BY SE PUEDE UTILIZAR UN ALIAS

-- && ME PERMITE REUTILIZAR UN VALOR YA ASIGNADO

SELECT
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SUELDO ACTUAL",
SUELDO_EMP+SUELDO_EMP+&&PORC_AUMENTO AS "SUELDO AUMENTADO",
SUELDO_EMP*&PORC_AUMENTO AS AUMENTO
FROM EMPLEADO
ORDER BY AUMENTO DESC; -- PARA EL ORDER BY SE PUEDE UTILIZAR UN ALIAS

SELECT
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SUELDO ACTUAL",
SUELDO_EMP+SUELDO_EMP+&&PORC_AUMENTO AS "SUELDO AUMENTADO",
SUELDO_EMP*&PORC_AUMENTO AS AUMENTO
FROM EMPLEADO 
WHERE &CONDICION -- ACA SE INTRODUCE LA CONDUCION DE FORMA MANUAL
ORDER BY AUMENTO DESC; -- PARA EL ORDER BY SE PUEDE UTILIZAR UN ALIAS

-- 'UNDEFINE' SIRVE PARA BORRAR DE LA MEMORIA LA VARIABLE &&

-- CASO 4 Y CASO 5 DE ACT 124 QUEDA DE TAREA PARA VIERNES 3 DE SEPT