SCRIPT CBD VIERNES 27-08-21

---

SELECT
NUMRUT_EMP, DVRUT_EMP, NOMBRE_EMP, APPATERNO_EMP, APMATERNO_EMP, SUELDO_EMP
FROM EMPLEADO
WHERE SUELDO_EMP <= 1500000
ORDER BY SUELDO_EMP DESC;

SELECT
NUMRUT_EMP, DVRUT_EMP, NOMBRE_EMP, APPATERNO_EMP, APMATERNO_EMP, SUELDO_EMP
FROM EMPLEADO
WHERE LOWER(NOMBRE_EMP) = LOWER('MARTA')
ORDER BY SUELDO_EMP DESC;

SELECT
NUMRUT_EMP, DVRUT_EMP, NOMBRE_EMP, APPATERNO_EMP, APMATERNO_EMP, ID_ESTCIVIL
FROM EMPLEADO
WHERE ID_ESTCIVIL <> 1;

SELECT
NUMRUT_EMP, DVRUT_EMP, NOMBRE_EMP, APPATERNO_EMP, APMATERNO_EMP, SUELDO_EMP
FROM EMPLEADO
WHERE SUELDO_EMP BETWEEN 300000 AND tel:1000000
ORDER BY SUELDO_EMP;

SELECT
NRO_PROPIEDAD, NRO_DORMITORIOS
FROM PROPIEDAD
WHERE NRO_DORMITORIOS = 1 OR NRO_DORMITORIOS = 2 OR NRO_DORMITORIOS = 3;

SELECT
NRO_PROPIEDAD, NRO_DORMITORIOS
FROM PROPIEDAD
WHERE NRO_DORMITORIOS IN (1,2,3);


SELECT
NUMRUT_EMP, DVRUT_EMP, NOMBRE_EMP, APPATERNO_EMP, APMATERNO_EMP, ID_ESTCIVIL
FROM EMPLEADO
WHERE APPATERNO_EMP LIKE '__A%';

SELECT
NRO_PROPIEDAD, NRO_DORMITORIOS,VALOR_GASTO_COMUN
FROM PROPIEDAD
WHERE VALOR_GASTO_COMUN IS NULL;

SELECT
NRO_PROPIEDAD, NRO_DORMITORIOS,VALOR_GASTO_COMUN
FROM PROPIEDAD
WHERE VALOR_GASTO_COMUN IS NOT NULL;