-- Ejemplo prueba N°1 del informe:

SELECT
NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
DIRECCION_PROPIEDAD AS "DIRECCIÓN",
SUPERFICIE, 
NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS", 
NRO_BANOS AS "CANTIDAD DE BAÑOS",
VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
ORDER BY FECHA_ENTREGA_PROPIEDAD;

-- Ejemplo prueba N°2 del informe

SELECT
NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
DIRECCION_PROPIEDAD AS "DIRECCIÓN",
SUPERFICIE, 
NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS", 
NRO_BANOS AS "CANTIDAD DE BAÑOS",
VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'MM/YYYY') = '02/2010'
ORDER BY FECHA_ENTREGA_PROPIEDAD;

-- Creación de tabla DET_PROPIEDADES_ARRIENDO_VENTA con AS SELECT

CREATE TABLE DET_PROPIEDADES_ARRIENDO_VENTA (
	NRO_PROPIEDAD NOT NULL CONSTRAINT PK_PDETALLE PRIMARY KEY, 
	FECHA_ENTREGA_PROPIEDAD NOT NULL, 
	DIRECCION_PROPIEDAD NOT NULL,
	SUPERFICIE NOT NULL,
	NRO_DORMITORIOS,
	NRO_BANOS,
	VALOR_ARRIENDO NOT NULL
	)

AS SELECT
	NRO_PROPIEDAD,
	FECHA_ENTREGA_PROPIEDAD,
	DIRECCION_PROPIEDAD,
	SUPERFICIE,
	NRO_DORMITORIOS,
	NRO_BANOS,
	VALOR_ARRIENDO

FROM PROPIEDAD;

-- Consulta de tabla creada

SELECT
	NRO_PROPIEDAD AS "NÚMERO",
	FECHA_ENTREGA_PROPIEDAD AS "ENTREGA",
	DIRECCION_PROPIEDAD AS "DIRECCIÓN",
	SUPERFICIE,
	NRO_DORMITORIOS AS "HABITACIONES",
	NRO_BANOS AS "BAÑOS",
	VALOR_ARRIENDO AS "VALOR ARRIENDO"

FROM DET_PROPIEDADES_ARRIENDO_VENTA

ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;
