SELECT
NUMRUT_EMP||'-'||DVRUT_EMP AS "RUN EMPLEADO",
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SALARIO ACTUAL",
SUELDO_EMP*((&VALOR_PORC)/100) AS "BONIFICACION EXTRA"
FROM EMPLEADO
WHERE ID_CATEGORIA_EMP NOT IN(3) AND SUELDO_EMP<500000
ORDER BY APPATERNO_EMP ASC;