-- CASO 1

SELECT 
TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') AS FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD 
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY');

-- &MI_VAR 

SELECT 
TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'DD/MM/YYYY') AS FECHA_ENTREGA_PROPIEDAD
FROM PROPIEDAD 
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'YYYY') = &ANNIO_CONSULTA; 

-- CASO 2

SELECT
NUMRUT_CLI||'-'||DVRUT_CLI AS "RUN CLIENTE",
APPATERNO_CLI||' '||APMATERNO_CLI||' '||NOMBRE_CLI AS "NOMBRE CLIENTE",
RENTA_CLI AS RENTA, FONOFIJO_CLI AS "TELEFONO FIJO", CELULAR_CLI AS CELULAR
FROM CLIENTE
WHERE (ID_ESTCIVIL IN(3,4) AND RENTA_CLI>=800000) OR ID_ESTCIVIL=1;

-- CASO 3

SELECT
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SUELDO ACTUAL",
SUELDO_EMP+SUELDO_EMP+&&PORC_AUMENTO AS "SUELDO REAJUSTADO",
SUELDO_EMP*&PORC_AUMENTO AS AUMENTO
FROM EMPLEADO 
WHERE &CONDICION 
ORDER BY AUMENTO DESC;

-- CASO 4

SELECT
NUMRUT_EMP||'-'||DVRUT_EMP AS "RUN EMPLEADO",
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SALARIO ACTUAL",
SUELDO_EMP*((&VALOR_PORC)/100) AS "BONIFICACION EXTRA"
FROM EMPLEADO
WHERE ID_CATEGORIA_EMP NOT IN(3) AND SUELDO_EMP<500000
ORDER BY APPATERNO_EMP ASC;

-- CASO 5

-- Ejemplo prueba N°1 del informe:

SELECT
NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
DIRECCION_PROPIEDAD AS "DIRECCIÓN",
SUPERFICIE, 
NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS", 
NRO_BANOS AS "CANTIDAD DE BAÑOS",
VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
ORDER BY FECHA_ENTREGA_PROPIEDAD;

-- Ejemplo prueba N°2 del informe

SELECT
NRO_PROPIEDAD AS "NUMERO PROPIEDAD",
FECHA_ENTREGA_PROPIEDAD AS "FECHA ENTREGA PROPIEDAD",
DIRECCION_PROPIEDAD AS "DIRECCIÓN",
SUPERFICIE, 
NRO_DORMITORIOS AS "CANTIDAD DE DORMITORIOS", 
NRO_BANOS AS "CANTIDAD DE BAÑOS",
VALOR_ARRIENDO AS "VALOR ARRIENDO"
FROM PROPIEDAD
WHERE TO_CHAR(FECHA_ENTREGA_PROPIEDAD, 'MM/YYYY') = '02/2010'
ORDER BY FECHA_ENTREGA_PROPIEDAD;

-- Creación de tabla DET_PROPIEDADES_ARRIENDO_VENTA con AS SELECT

CREATE TABLE DET_PROPIEDADES_ARRIENDO_VENTA (
	NRO_PROPIEDAD NOT NULL CONSTRAINT PK_PDETALLE PRIMARY KEY, 
	FECHA_ENTREGA_PROPIEDAD NOT NULL, 
	DIRECCION_PROPIEDAD NOT NULL,
	SUPERFICIE NOT NULL,
	NRO_DORMITORIOS,
	NRO_BANOS,
	VALOR_ARRIENDO NOT NULL
	)

AS SELECT
	NRO_PROPIEDAD,
	FECHA_ENTREGA_PROPIEDAD,
	DIRECCION_PROPIEDAD,
	SUPERFICIE,
	NRO_DORMITORIOS,
	NRO_BANOS,
	VALOR_ARRIENDO

FROM PROPIEDAD;

-- Consulta de tabla creada

SELECT
	NRO_PROPIEDAD AS "NÚMERO",
	FECHA_ENTREGA_PROPIEDAD AS "ENTREGA",
	DIRECCION_PROPIEDAD AS "DIRECCIÓN",
	SUPERFICIE,
	NRO_DORMITORIOS AS "HABITACIONES",
	NRO_BANOS AS "BAÑOS",
	VALOR_ARRIENDO AS "VALOR ARRIENDO"

FROM DET_PROPIEDADES_ARRIENDO_VENTA

ORDER BY FECHA_ENTREGA_PROPIEDAD ASC;
