-- TAREA114

-- USANDO CASE, con 0

SELECT
NUMRUT_CLI||'-'||DVRUT_CLI AS RUT,
NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI AS "NOMBRE COMPLETO",
RENTA_CLI AS "RENTA",
FONOFIJO_CLI AS "TELEFONO FIJO",
CASE WHEN (CELULAR_CLI IS NULL) THEN 0 ELSE CELULAR_CLI END AS "TELEFONO MOVIL"
FROM CLIENTE;

-- con TO_CHAR

SELECT
NUMRUT_CLI||'-'||DVRUT_CLI AS RUT,
NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI AS "NOMBRE COMPLETO",
RENTA_CLI AS RENTA,
FONOFIJO_CLI AS "TELEFONO FIJO",
CASE WHEN (CELULAR_CLI IS NULL) THEN 'SIN CELULAR' ELSE to_char(CELULAR_CLI) END AS "TELEFONO MOVIL"
FROM CLIENTE;

-- con NVL

-- con 0

SELECT
NUMRUT_CLI AS "NUMERO RUT", DVRUT_CLI AS "DIGITO VERIFICADOR",
NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI "NOMBRE COMPLETO",
RENTA_CLI AS "RENTA",
FONOFIJO_CLI AS "TELEFONO FIJO",
NVL(CELULAR_CLI, 0) AS "CELULAR"
FROM CLIENTE
ORDER BY APPATERNO_CLI ASC, APMATERNO_CLI ASC;

-- CON TO_CHAR

SELECT
NUMRUT_CLI AS "NUMERO RUT", DVRUT_CLI AS "DIGITO VERIFICADOR",
NOMBRE_CLI||' '||APPATERNO_CLI||' '||APMATERNO_CLI AS "NOMBRE COMPLETO",
RENTA_CLI AS "RENTA",
FONOFIJO_CLI AS "TELEFONO FIJO",
NVL(to_char(CELULAR_CLI), 'SIN CELULAR') AS "CELULAR"
FROM CLIENTE
ORDER BY APPATERNO_CLI ASC, APMATERNO_CLI ASC;

---- OTRO CASO

SELECT
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SUELDO",
(SUELDO_EMP*50/100) AS "BONO POR CAPACITACIÓN"
FROM EMPLEADO
ORDER BY SUELDO_EMP*0.5 DESC;

-- CASO 4

SELECT
NRO_PROPIEDAD AS "NRO PROPIEDAD",
NUMRUT_PROP AS "RUT PROPIETARIO",
DIRECCION_PROPIEDAD AS "DIRECCION",
VALOR_ARRIENDO AS "VALOR ARRIENDO",
VALOR_ARRIENDO*0.054 AS "VALOR COMPENSACIÓN"
FROM PROPIEDAD
ORDER BY NUMRUT_PROP ASC;

-- CASO 5

SELECT
NUMRUT_EMP||'-'||DVRUT_EMP AS "RUN EMPLEADO",
NOMBRE_EMP||'-'||APPATERNO_EMP||'-'||APPMATERNO AS "NOMBRE COMPLETO",
SUELDO_EMP AS "SALARIO ACTUAL",
SUELDO_EMP+SUELDO_EMP*0.135 AS "SALARIO REAJUSTADO", -- SUELDO_EMP*1.135 VALE TAMBIEN
SUELDO_EMP*0.135 AS "REAJUSTE"
FROM EMPLEADO
ORDER BY SUELDO_EMP*0.135 ASC, APPATERNO_EMP ASC;

-- CON FUNCION ROUND

SELECT
NUMRUT_EMP||'-'||DVRUT_EMP AS "RUN EMPLEADO",
NOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLEADO",
SUELDO_EMP AS "SALARIO ACTUAL",
ROUND(SUELDO_EMP+(SUELDO_EMP*0.135)) AS "SALARIO REAJUSTADO",
ROUND(SUELDO_EMP*0.135) AS REAJUSTE
FROM EMPLEADO
ORDER BY SUELDO_EMP*0.135 ASC, APPATERNO_EMP ASC;