
--TO_CHAR()
SELECT TO_CHAR(500000, 'L000G000G000') FROM DUAL;

--TO_DATE()
SELECT TO_DATE('01/01/2021')+1 FROM DUAL;
SELECT TO_DATE('12/25/2021', 'MM/DD/YYYY')+1 FROM DUAL;
SELECT TO_DATE('2021/25/11', 'YYYY/DD/MM')+1 FROM DUAL;

--NVL()
SELECT NVL(NULL, 'TIENE NULO') FROM DUAL;
SELECT NVL(TO_CHAR(FONO_FIJO_EMP), 'NO TIENE FONO') FROM EMPLEADO;

--NVL2()
SELECT NVL2(NULL, 'TIENE VALOR', 'TIENE VALOR NULL') FROM DUAL; 
SELECT NVL2(FONO_FIJO_EMP, TO_CHAR(FONO_FIJO_EMP), 'NO TIENE FONO') FROM EMPLEADO;

--NULLIF()
SELECT NULLIF(10,10) FROM DUAL; --DEVUELVE NULL CON IGUALDAD EN LOS 2 ARGUMENTOS
SELECT NULLIF(15,10) FROM DUAL; --DEVUELVE EL PRIMER ARGUMENTO

--COALESCE()
SELECT COALESCE(COLUMN1, COLUMN2, COLUMN3, ETC, 'SIN NOMBRE') FROM TABLA; --RETORNA EL PRIMER DATO Q NO ES NULO

--CASE
SELECT
PNOMBRE_CLI, APPATERNO_CLI, ID_ESTADO_CIVIL,
CASE ID_ESTADO ID_ESTADO_CIVIL
	WHEN 10 THEN 'CASADO/A' --SIEMPRE DEBE DEVOLVER EL MISMO TIPO DE DATO
	WHEN 20 THEN 'DIVORCIADO/A' --EN CADA LINEA
	WHEN 30 THEN 'SOLTERO/A'
	WHEN 40 THEN 'VIUDO/A'
	WHEN 50 THEN 'SEPARADO/A'
	WHEN 60 THEN 'ACUERDO DE UNION CIVIL'
END AS DESCRIPCION_ESTADO_CIVIL
FROM CLIENTE;

SELECT
PNOMBRE_CLI, APPATERNO_CLI,
CASE
	WHEN RENTA <300000 THEN 0.6
	WHEN RENTA BETWEEN 300000 AND 500000 THEN 0.5
	WHEN RENTA BETWEEN 500001 AND 1000000 THEN 0.4
	WHEN RENTA BETWEEN 1000001 AND 2000000 THEN 0.3
	ELSE 0.1
END AS PORCENTAJE_DESCUENTO
FROM CLIENTE;

--DECODE-PERMITE TOMAR UNA COLUMNA TAMBIEN
SELECT
PNOMBRE_CLI, APPATERNO_CLI,
DECODE(ID_ESTADO_CIVIL, 10, 'CASADO/A' --CUANDO ESTADO CIVIL = 10 ENTONCES 'CASADO'
					  , 20, 'DIVORCIADO/A'
					  , 30, 'SOLTERO/A'
					  , 40, 'VIUDO/A'
					  , 'ESTADO CIVIL NO DISPONIBLE'
) AS DESCRIPCION_ESTADO_CIVIL
FROM CLIENTE;