SELECT
NUMRUN_EMP||'-'||DVRUN_EMP AS "RUN EMPLEADO",
PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP AS "NOMBRE EMPLADO",
ROUND(MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATO)/12) AS "AÑOS CONTRATADO",
TO_CHAR(SUELDO_BASE, 'L999G999G999') AS "SUELDO BASE",
TO_CHAR(ROUND(SUELDO_BASE * ROUND(MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATO)/12)/100), 'L999G999G999') AS "VALOR MOVILIZACIÓN",

TO_CHAR(ROUND(SUELDO_BASE*((CASE 
    WHEN SUELDO_BASE >= 450000 THEN SUBSTR(TO_CHAR(SUELDO_BASE), 0, 1)
    WHEN SUELDO_BASE < 450000 THEN SUBSTR(TO_CHAR(SUELDO_BASE), 0, 2)
END)/100)), 'L999G999G999') AS "BONIF. EXTRA MOVILIZACION",

TO_CHAR(ROUND(SUELDO_BASE * ROUND(MONTHS_BETWEEN(SYSDATE, FECHA_CONTRATO)/12)/100) +
ROUND(SUELDO_BASE*((CASE 
    WHEN SUELDO_BASE >= 450000 THEN SUBSTR(TO_CHAR(SUELDO_BASE), 0, 1)
    WHEN SUELDO_BASE < 450000 THEN SUBSTR(TO_CHAR(SUELDO_BASE), 0, 2)
END)/100)),'L999G999G999') AS "VALOR MOVILIZACION TOTAL"

FROM EMPLEADO
WHERE ID_COMUNA IN(117, 118, 120, 122)
ORDER BY APPATERNO_EMP;